// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Iris.Web.Controllers
{
    public partial class CommentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CommentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PostComments()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PostComments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddUserPostComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserPostComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAnonymousPostComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAnonymousPostComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddPostComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddPostComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PageComments()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PageComments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddUserPageComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserPageComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAnonymousPageComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAnonymousPageComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddPageComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddPageComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ArticleComments()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticleComments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddUserArticleComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserArticleComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAnonymousArticleComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAnonymousArticleComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddArticleComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddArticleComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Like()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Like);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DisLike()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisLike);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CommentController Actions { get { return MVC.Comment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Comment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Comment";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PostComments = "PostComments";
            public readonly string AddUserPostComment = "AddUserPostComment";
            public readonly string AddAnonymousPostComment = "AddAnonymousPostComment";
            public readonly string AddPostComment = "AddPostComment";
            public readonly string PageComments = "PageComments";
            public readonly string AddUserPageComment = "AddUserPageComment";
            public readonly string AddAnonymousPageComment = "AddAnonymousPageComment";
            public readonly string AddPageComment = "AddPageComment";
            public readonly string ArticleComments = "ArticleComments";
            public readonly string AddUserArticleComment = "AddUserArticleComment";
            public readonly string AddAnonymousArticleComment = "AddAnonymousArticleComment";
            public readonly string AddArticleComment = "AddArticleComment";
            public readonly string PostUserComments = "PostUserComments";
            public readonly string PageUserComments = "PageUserComments";
            public readonly string ArticleUserComments = "ArticleUserComments";
            public readonly string Like = "Like";
            public readonly string DisLike = "DisLike";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PostComments = "PostComments";
            public const string AddUserPostComment = "AddUserPostComment";
            public const string AddAnonymousPostComment = "AddAnonymousPostComment";
            public const string AddPostComment = "AddPostComment";
            public const string PageComments = "PageComments";
            public const string AddUserPageComment = "AddUserPageComment";
            public const string AddAnonymousPageComment = "AddAnonymousPageComment";
            public const string AddPageComment = "AddPageComment";
            public const string ArticleComments = "ArticleComments";
            public const string AddUserArticleComment = "AddUserArticleComment";
            public const string AddAnonymousArticleComment = "AddAnonymousArticleComment";
            public const string AddArticleComment = "AddArticleComment";
            public const string PostUserComments = "PostUserComments";
            public const string PageUserComments = "PageUserComments";
            public const string ArticleUserComments = "ArticleUserComments";
            public const string Like = "Like";
            public const string DisLike = "DisLike";
        }


        static readonly ActionParamsClass_PostComments s_params_PostComments = new ActionParamsClass_PostComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PostComments PostCommentsParams { get { return s_params_PostComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PostComments
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddUserPostComment s_params_AddUserPostComment = new ActionParamsClass_AddUserPostComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddUserPostComment AddUserPostCommentParams { get { return s_params_AddUserPostComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddUserPostComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddAnonymousPostComment s_params_AddAnonymousPostComment = new ActionParamsClass_AddAnonymousPostComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAnonymousPostComment AddAnonymousPostCommentParams { get { return s_params_AddAnonymousPostComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAnonymousPostComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddPostComment s_params_AddPostComment = new ActionParamsClass_AddPostComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddPostComment AddPostCommentParams { get { return s_params_AddPostComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddPostComment
        {
            public readonly string id = "id";
            public readonly string replyId = "replyId";
        }
        static readonly ActionParamsClass_PageComments s_params_PageComments = new ActionParamsClass_PageComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PageComments PageCommentsParams { get { return s_params_PageComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PageComments
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddUserPageComment s_params_AddUserPageComment = new ActionParamsClass_AddUserPageComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddUserPageComment AddUserPageCommentParams { get { return s_params_AddUserPageComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddUserPageComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddAnonymousPageComment s_params_AddAnonymousPageComment = new ActionParamsClass_AddAnonymousPageComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAnonymousPageComment AddAnonymousPageCommentParams { get { return s_params_AddAnonymousPageComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAnonymousPageComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddPageComment s_params_AddPageComment = new ActionParamsClass_AddPageComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddPageComment AddPageCommentParams { get { return s_params_AddPageComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddPageComment
        {
            public readonly string id = "id";
            public readonly string replyId = "replyId";
        }
        static readonly ActionParamsClass_ArticleComments s_params_ArticleComments = new ActionParamsClass_ArticleComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArticleComments ArticleCommentsParams { get { return s_params_ArticleComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArticleComments
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddUserArticleComment s_params_AddUserArticleComment = new ActionParamsClass_AddUserArticleComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddUserArticleComment AddUserArticleCommentParams { get { return s_params_AddUserArticleComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddUserArticleComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddAnonymousArticleComment s_params_AddAnonymousArticleComment = new ActionParamsClass_AddAnonymousArticleComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAnonymousArticleComment AddAnonymousArticleCommentParams { get { return s_params_AddAnonymousArticleComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAnonymousArticleComment
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddArticleComment s_params_AddArticleComment = new ActionParamsClass_AddArticleComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddArticleComment AddArticleCommentParams { get { return s_params_AddArticleComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddArticleComment
        {
            public readonly string id = "id";
            public readonly string replyId = "replyId";
        }
        static readonly ActionParamsClass_PostUserComments s_params_PostUserComments = new ActionParamsClass_PostUserComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PostUserComments PostUserCommentsParams { get { return s_params_PostUserComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PostUserComments
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_PageUserComments s_params_PageUserComments = new ActionParamsClass_PageUserComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PageUserComments PageUserCommentsParams { get { return s_params_PageUserComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PageUserComments
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_ArticleUserComments s_params_ArticleUserComments = new ActionParamsClass_ArticleUserComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArticleUserComments ArticleUserCommentsParams { get { return s_params_ArticleUserComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArticleUserComments
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_Like s_params_Like = new ActionParamsClass_Like();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Like LikeParams { get { return s_params_Like; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Like
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DisLike s_params_DisLike = new ActionParamsClass_DisLike();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisLike DisLikeParams { get { return s_params_DisLike; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisLike
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AddAnonymousArticleComment = "_AddAnonymousArticleComment";
                public readonly string _AddAnonymousPageComment = "_AddAnonymousPageComment";
                public readonly string _AddAnonymousPostComment = "_AddAnonymousPostComment";
                public readonly string _AddUserArticleComment = "_AddUserArticleComment";
                public readonly string _AddUserPageComment = "_AddUserPageComment";
                public readonly string _AddUserPostComment = "_AddUserPostComment";
                public readonly string _ArticleComments = "_ArticleComments";
                public readonly string _ArticleUserComments = "_ArticleUserComments";
                public readonly string _CommentClosed = "_CommentClosed";
                public readonly string _PageComments = "_PageComments";
                public readonly string _PageUserComments = "_PageUserComments";
                public readonly string _PostComments = "_PostComments";
                public readonly string _PostUserComments = "_PostUserComments";
            }
            public readonly string _AddAnonymousArticleComment = "~/Views/Comment/_AddAnonymousArticleComment.cshtml";
            public readonly string _AddAnonymousPageComment = "~/Views/Comment/_AddAnonymousPageComment.cshtml";
            public readonly string _AddAnonymousPostComment = "~/Views/Comment/_AddAnonymousPostComment.cshtml";
            public readonly string _AddUserArticleComment = "~/Views/Comment/_AddUserArticleComment.cshtml";
            public readonly string _AddUserPageComment = "~/Views/Comment/_AddUserPageComment.cshtml";
            public readonly string _AddUserPostComment = "~/Views/Comment/_AddUserPostComment.cshtml";
            public readonly string _ArticleComments = "~/Views/Comment/_ArticleComments.cshtml";
            public readonly string _ArticleUserComments = "~/Views/Comment/_ArticleUserComments.cshtml";
            public readonly string _CommentClosed = "~/Views/Comment/_CommentClosed.cshtml";
            public readonly string _PageComments = "~/Views/Comment/_PageComments.cshtml";
            public readonly string _PageUserComments = "~/Views/Comment/_PageUserComments.cshtml";
            public readonly string _PostComments = "~/Views/Comment/_PostComments.cshtml";
            public readonly string _PostUserComments = "~/Views/Comment/_PostUserComments.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CommentController : Iris.Web.Controllers.CommentController
    {
        public T4MVC_CommentController() : base(Dummy.Instance) { }

        partial void PostCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult PostComments(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PostComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PostCommentsOverride(callInfo, id);
            return callInfo;
        }

        partial void AddUserPostCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Iris.Model.AddUserCommentModel model);

        public override System.Web.Mvc.ActionResult AddUserPostComment(Iris.Model.AddUserCommentModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserPostComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddUserPostCommentOverride(callInfo, model);
            return callInfo;
        }

        partial void AddAnonymousPostCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Iris.Model.AddAnonymousCommentModel model);

        public override System.Web.Mvc.ActionResult AddAnonymousPostComment(Iris.Model.AddAnonymousCommentModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAnonymousPostComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAnonymousPostCommentOverride(callInfo, model);
            return callInfo;
        }

        partial void AddPostCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int? replyId);

        public override System.Web.Mvc.ActionResult AddPostComment(int id, int? replyId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddPostComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyId", replyId);
            AddPostCommentOverride(callInfo, id, replyId);
            return callInfo;
        }

        partial void PageCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult PageComments(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PageComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PageCommentsOverride(callInfo, id);
            return callInfo;
        }

        partial void AddUserPageCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Iris.Model.AddUserCommentModel model);

        public override System.Web.Mvc.ActionResult AddUserPageComment(Iris.Model.AddUserCommentModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserPageComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddUserPageCommentOverride(callInfo, model);
            return callInfo;
        }

        partial void AddAnonymousPageCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Iris.Model.AddAnonymousCommentModel model);

        public override System.Web.Mvc.ActionResult AddAnonymousPageComment(Iris.Model.AddAnonymousCommentModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAnonymousPageComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAnonymousPageCommentOverride(callInfo, model);
            return callInfo;
        }

        partial void AddPageCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int? replyId);

        public override System.Web.Mvc.ActionResult AddPageComment(int id, int? replyId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddPageComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyId", replyId);
            AddPageCommentOverride(callInfo, id, replyId);
            return callInfo;
        }

        partial void ArticleCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult ArticleComments(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticleComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ArticleCommentsOverride(callInfo, id);
            return callInfo;
        }

        partial void AddUserArticleCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Iris.Model.AddUserCommentModel model);

        public override System.Web.Mvc.ActionResult AddUserArticleComment(Iris.Model.AddUserCommentModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserArticleComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddUserArticleCommentOverride(callInfo, model);
            return callInfo;
        }

        partial void AddAnonymousArticleCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Iris.Model.AddAnonymousCommentModel model);

        public override System.Web.Mvc.ActionResult AddAnonymousArticleComment(Iris.Model.AddAnonymousCommentModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAnonymousArticleComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddAnonymousArticleCommentOverride(callInfo, model);
            return callInfo;
        }

        partial void AddArticleCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int? replyId);

        public override System.Web.Mvc.ActionResult AddArticleComment(int id, int? replyId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddArticleComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "replyId", replyId);
            AddArticleCommentOverride(callInfo, id, replyId);
            return callInfo;
        }

        partial void PostUserCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        public override System.Web.Mvc.ActionResult PostUserComments(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PostUserComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            PostUserCommentsOverride(callInfo, page, count);
            return callInfo;
        }

        partial void PageUserCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        public override System.Web.Mvc.ActionResult PageUserComments(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PageUserComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            PageUserCommentsOverride(callInfo, page, count);
            return callInfo;
        }

        partial void ArticleUserCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        public override System.Web.Mvc.ActionResult ArticleUserComments(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArticleUserComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ArticleUserCommentsOverride(callInfo, page, count);
            return callInfo;
        }

        partial void LikeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult Like(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Like);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LikeOverride(callInfo, id);
            return callInfo;
        }

        partial void DisLikeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult DisLike(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisLike);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DisLikeOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
