// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Alert = "_Alert";
                public readonly string _Layout = "_Layout";
                public readonly string _MINIPROFILER_UPDATED_Layout = "_MINIPROFILER UPDATED Layout";
                public readonly string _ValidationSummery = "_ValidationSummery";
                public readonly string DefaultCaptcha = "DefaultCaptcha";
                public readonly string Error = "Error";
            }
            public readonly string _Alert = "~/Views/Shared/_Alert.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _MINIPROFILER_UPDATED_Layout = "~/Views/Shared/_MINIPROFILER UPDATED Layout.cshtml";
            public readonly string _ValidationSummery = "~/Views/Shared/_ValidationSummery.cshtml";
            public readonly string DefaultCaptcha = "~/Views/Shared/DefaultCaptcha.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string MenuHelperModel = "MenuHelperModel";
                public readonly string MenuHelperModel_cshtml = "MenuHelperModel";
                public readonly string SiteMapHelperModel = "SiteMapHelperModel";
                public readonly string SiteMapHelperModel_cshtml = "SiteMapHelperModel";
                public readonly string SiteMapNodeModel = "SiteMapNodeModel";
                public readonly string SiteMapNodeModel_cshtml = "SiteMapNodeModel";
                public readonly string SiteMapNodeModelList = "SiteMapNodeModelList";
                public readonly string SiteMapNodeModelList_cshtml = "SiteMapNodeModelList";
                public readonly string SiteMapPathHelperModel = "SiteMapPathHelperModel";
                public readonly string SiteMapPathHelperModel_cshtml = "SiteMapPathHelperModel";
                public readonly string SiteMapTitleHelperModel = "SiteMapTitleHelperModel";
                public readonly string SiteMapTitleHelperModel_cshtml = "SiteMapTitleHelperModel";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
